apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -f docker-compose.yml convert
      -o capi-yolov8-ensemble/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: camera-simulator0
  name: camera-simulator0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: camera-simulator0
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -f docker-compose.yml convert
          -o capi-yolov8-ensemble/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: camera-simulator0
    spec:
      containers:
      - args:
        - |
          if [ ! -f /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 ]; then
             mkdir -p /home/pipeline-server/sample-media
             wget -O /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 https://www.pexels.com/download/video/4465029
          fi
          ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_0
        command:
        - /bin/sh
        - -c
        image: jrottenberg/ffmpeg:4.1-alpine
        imagePullPolicy: ""
        name: camera-simulator0
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
