apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -f docker-compose.yml convert
      -o capi-yolov8-ensemble/
    kompose.version: 1.21.0 (992df58d8)
    kompose.volume.storage-class-name: yolov8-ensemble-storage
    kompose.volume.type: hostPath
  creationTimestamp: null
  labels:
    io.kompose.service: capiyolov8ensemble
  name: capiyolov8ensemble
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: capiyolov8ensemble
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -f docker-compose.yml convert
          -o capi-yolov8-ensemble/
        kompose.version: 1.21.0 (992df58d8)
        kompose.volume.storage-class-name: yolov8-ensemble-storage
        kompose.volume.type: hostPath
      creationTimestamp: null
      labels:
        io.kompose.service: capiyolov8ensemble
    spec:
      containers:
      - command:
        - /app/gst-ovms/pipelines/yolov8_ensemble/yolo_efficientnet_helm.sh
        env:
        - name: BARCODE
          value: "0"
        - name: CONTAINER_NAME
          value: '"capi_yolov8_ensemble"'
        - name: DC
          valueFrom:
            configMapKeyRef:
              key: DC
              name: capi-yolov8-ensemble-env
        - name: DETECTION_THRESHOLD
          valueFrom:
            configMapKeyRef:
              key: DETECTION_THRESHOLD
              name: capi-yolov8-ensemble-env
        - name: DEVICE
          value: CPU
        - name: DISPLAY
          value: :0
        - name: GST_DEBUG
          valueFrom:
            configMapKeyRef:
              key: GST_DEBUG
              name: capi-yolov8-ensemble-env
        - name: GST_VAAPI_DRM_DEVICE
          valueFrom:
            configMapKeyRef:
              key: GST_VAAPI_DRM_DEVICE
              name: capi-yolov8-ensemble-env
        - name: INPUTSRC
          value: rtsp://localhost:8554/camera_1
        - name: INPUT_TYPE
          valueFrom:
            configMapKeyRef:
              key: INPUT_TYPE
              name: capi-yolov8-ensemble-env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: capi-yolov8-ensemble-env
        - name: NO_BASH_C
          valueFrom:
            configMapKeyRef:
              key: NO_BASH_C
              name: capi-yolov8-ensemble-env
        - name: OVMS_MODEL_CONFIG_JSON
          value: /app/gst-ovms/pipelines/yolov8_ensemble/config-yolov8.json
        - name: PIPELINE_EXEC_PATH
          valueFrom:
            configMapKeyRef:
              key: PIPELINE_EXEC_PATH
              name: capi-yolov8-ensemble-env
        - name: PIPELINE_PROFILE
          value: capi_yolov8_ensemble
        - name: RENDER_MODE
          valueFrom:
            configMapKeyRef:
              key: RENDER_MODE
              name: capi-yolov8-ensemble-env
        - name: RENDER_PORTRAIT_MODE
          valueFrom:
            configMapKeyRef:
              key: RENDER_PORTRAIT_MODE
              name: capi-yolov8-ensemble-env
        - name: TARGET_GPU_DEVICE
          valueFrom:
            configMapKeyRef:
              key: TARGET_GPU_DEVICE
              name: capi-yolov8-ensemble-env
        - name: USE_ONEVPL
          valueFrom:
            configMapKeyRef:
              key: USE_ONEVPL
              name: capi-yolov8-ensemble-env
        - name: WINDOW_HEIGHT
          valueFrom:
            configMapKeyRef:
              key: WINDOW_HEIGHT
              name: capi-yolov8-ensemble-env
        - name: WINDOW_WIDTH
          valueFrom:
            configMapKeyRef:
              key: WINDOW_WIDTH
              name: capi-yolov8-ensemble-env
        - name: cl_cache_dir
          valueFrom:
            configMapKeyRef:
              key: cl_cache_dir
              name: capi-yolov8-ensemble-env
        image: yolov8capiensemble:dev
        imagePullPolicy: ""
        name: capiyolov8ensemble
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp/results
          name: capiyolov8ensemble-claim0
        - mountPath: /home/dlstreamer/.Xauthority
          name: capiyolov8ensemble-claim1
        - mountPath: /tmp/.X11-unix
          name: capiyolov8ensemble-claim2
        - mountPath: /home/pipeline-server/.cl-cache
          name: capiyolov8ensemble-claim3
        - mountPath: /home/pipeline-server/envs
          name: capiyolov8ensemble-claim4
        - mountPath: /models
          name: capiyolov8ensemble-claim5
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: capiyolov8ensemble-claim0
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim0
      - name: capiyolov8ensemble-claim1
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim1
      - name: capiyolov8ensemble-claim2
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim2
      - name: capiyolov8ensemble-claim3
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim3
      - name: capiyolov8ensemble-claim4
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim4
      - name: capiyolov8ensemble-claim5
        persistentVolumeClaim:
          claimName: capiyolov8ensemble-claim5
status: {}
