#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $

version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
  camera-simulator0:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-simulator0
    entrypoint: ["/bin/sh","-c"]
    command: 
    - | 
       if [ ! -f /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 ]; then
          mkdir -p /home/pipeline-server/sample-media
          wget -O /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 https://www.pexels.com/download/video/4465029
       fi
       ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_0
    depends_on:
      - camera-simulator
  camera-simulator1:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-simulator1
    entrypoint: ["/bin/sh","-c"]
    command: 
    - | 
       if [ ! -f /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 ]; then
          mkdir -p /home/pipeline-server/sample-media
          wget -O /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 https://www.pexels.com/download/video/4465029
       fi
       ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_1
    depends_on:
      - camera-simulator

  capiyolov8ensemble:
    image: yolov8capiensemble:dev
    deploy:
      mode: replicated
      replicas: 1
    network_mode: "host"
    privileged: true
    entrypoint: /app/gst-ovms/pipelines/yolov8_ensemble/yolo_efficientnet_helm.sh
    env_file:
      - capi-yolov8-ensemble-env
    environment:
      - CONTAINER_NAME="capi_yolov8_ensemble"
      - INPUTSRC=rtsp://camera-simulator:8554/camera_1
      - USE_ONEVPL=0
      - DEVICE=CPU
      - BARCODE=0
      - RENDER_MODE=${RENDER_MODE} #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
      - OVMS_MODEL_CONFIG_JSON=/app/gst-ovms/pipelines/yolov8_ensemble/config-yolov8.json
      - PIPELINE_PROFILE=capi_yolov8_ensemble
      - RESULT_USE_MQTT=1
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
    depends_on:
      - camera-simulator1
      - mqtt-broker
    volumes:
      - $RESULTS_DIR:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
      - ~/.cl-cache:/home/pipeline-server/.cl-cache

  mqtt-broker:
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto-no-auth.conf
    container_name: mqtt-broker
    hostname: mqtt-broker
    image: eclipse-mosquitto:2.0.19
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
