# Copyright © 2024 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

.PHONY: run

run:
	@pip3 install -r requirements.txt
	@TEST_DIR="../" python3 use-cases_smoke_tests.py
