#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

# Use an appropriate base image
FROM python:3.12

# Set environment variables
ENV DEBIAN_FRONTEND noninteractive
# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libopencv-dev \
     && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app
# Copy your classification code
COPY . /app
# Install Tensorflow-keras and other dependencies
RUN pip3 install -r requirements-tensorflow-keras.txt

ENV QT_DEBUG_PLUGINS=1
ENV DISPLAY=0