name: Build docker images

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-continual_learning:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Make Docker images for continual_learning
            run: |
              cd ./use-cases/continual_learning && make build
  build-dlstreamer_ovms:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Make Docker images for dlstreamer_ovms
            run: cd ./use-cases/dlstreamer && make build
          - name: Make Docker images for dlstreamer_ovms RealSense
            run: cd ./use-cases/dlstreamer && make build-realsense
  build-grpc_golang:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v4
            with: 
              go-version: '1.20.2'
          - name: Make Docker images for grpc_go
            run: |
              cd ./use-cases/grpc_go && make build
  build-grpc_python:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Make Docker images for grpc_python
            run: |
              cd ./use-cases/grpc_python && make build
  build-gst_capi:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Make Docker images for gst_capi face detection
            run: cd ./use-cases/gst_capi && make build_face_detection
          - name: Make Docker images for gst_capi yolov5
            run: cd ./use-cases/gst_capi && make build_capi_yolov5
          - name: Make Docker images for gst_capi capi yolov5 ensemble
            run: cd ./use-cases/gst_capi && make build_capi_yolov5_ensemble
          - name: Make Docker images for gst_capi yolov8
            run: cd ./use-cases/gst_capi && make build_capi_yolov8_ensemble
